// C++ code
//
/*
  MIDI Player for Passive Buzzer
  Plays a song (converted from a MIDI file via midi_to_arduino.py)
  on a passive buzzer using tone().

  1. Run midi_to_arduino.py on your .mid file to generate "song.h"
  2. Put song.h in the same folder as this .ino file
  3. Upload this sketch

  Wiring: passive buzzer (+) to pin 8, (-) to GND.
  (Any PWM-capable or even non-PWM digital pin works for tone().)
*/

#include "song.h"  // generated by midi_to_arduino.py - contains song_freq[], song_dur[], song_length

const int buzzerPin = 8;

// Articulation gap: a brief silence carved OUT of each note's own duration
// (not added on top of it) so repeated same-pitch notes are distinguishable.
// Because it's subtracted rather than added, total playback time still
// matches the original MIDI beat exactly - no drift.
const unsigned int articulationGapMs = 15;

unsigned int currentNote = 0;

void setup()
{
  pinMode(buzzerPin, OUTPUT);
}

void loop()
{
  if (currentNote < song_length) {
    unsigned int freq = pgm_read_word(&song_freq[currentNote]);
    unsigned int dur  = pgm_read_word(&song_dur[currentNote]);

    // Only carve out a gap if the note is long enough to afford it;
    // very short notes play full-length with no gap so fast passages
    // don't get audibly chopped or shortened.
    unsigned int gap = (dur > articulationGapMs * 2) ? articulationGapMs : 0;
    unsigned int soundDur = dur - gap;

    if (freq > 0) {
      tone(buzzerPin, freq, soundDur);
    } else {
      noTone(buzzerPin); // freq of 0 = a rest/pause
    }

    delay(dur); // always wait the FULL original duration, keeping the beat locked to the source timing
    currentNote++;
  }
  // once currentNote reaches song_length, loop() does nothing further (song finished)
}
